openapi: 3.0.3
info:
  title: Card Token API
  description: An API to tokenize sensitive card data, specifically the CVV, and to retrieve card information with the tokenized CVV.
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server
paths:
  /cardtokenapi/1.0.0/tokenize:
    post:
      summary: Tokenize a card's CVV
      description: Accepts full card information and returns a token for the CVV. The original CVV is not stored.
      requestBody:
        description: Card information to tokenize
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardTokenizationRequest'
            examples:
              tokenizeCvv:
                value:
                  cardholderName: 'John Doe'
                  cardNumber: '4111222233334444'
                  expiryDate: '12/25'
                  cvv: '123'
      responses:
        '201':
          description: CVV successfully tokenized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardTokenizationResponse'
              examples:
                tokenizeResponse:
                  value:
                    tokenizedCvv: 'tkn_abCdeF1gH2iJ3kL4mN'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidInput:
                  value:
                    code: '400'
                    message: 'Invalid card number or format.'
  /cardtokenapi/1.0.0/search:
    get:
      summary: Search for card information
      description: Retrieves card details using the card number. The returned CVV is the tokenized value.
      parameters:
        - name: cardNumber
          in: query
          description: The full card number to search for.
          required: true
          schema:
            type: string
            pattern: '^\d{16}$'
          examples:
            exampleCard:
              value: '4111222233334444'
      responses:
        '200':
          description: Card information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardInfoResponse'
              examples:
                cardFound:
                  value:
                    cardholderName: 'John Doe'
                    cardNumber: '4111222233334444'
                    expiryDate: '12/25'
                    tokenizedCvv: 'tkn_abCdeF1gH2iJ3kL4mN'
        '404':
          description: Card not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                notFound:
                  value:
                    code: '404'
                    message: 'Card number not found.'
components:
  schemas:
    CardTokenizationRequest:
      type: object
      required:
        - cardholderName
        - cardNumber
        - expiryDate
        - cvv
      properties:
        cardholderName:
          type: string
          description: The name of the cardholder.
          example: 'John Doe'
        cardNumber:
          type: string
          description: The 16-digit credit card number.
          pattern: '^\d{16}$'
          example: '4111222233334444'
        expiryDate:
          type: string
          description: The card's expiration date in MM/YY format.
          pattern: '^(0[1-9]|1[0-2])\/\d{2}$'
          example: '12/25'
        cvv:
          type: string
          description: The 3 or 4-digit card verification value.
          pattern: '^\d{3,4}$'
          example: '123'
    CardTokenizationResponse:
      type: object
      properties:
        tokenizedCvv:
          type: string
          description: The tokenized representation of the CVV.
          example: 'tkn_abCdeF1gH2iJ3kL4mN'
    CardInfoResponse:
      type: object
      properties:
        cardholderName:
          type: string
          description: The name of the cardholder.
          example: 'John Doe'
        cardNumber:
          type: string
          description: The card number.
          example: '4111222233334444'
        expiryDate:
          type: string
          description: The card's expiration date.
          example: '12/25'
        tokenizedCvv:
          type: string
          description: The tokenized CVV.
          example: 'tkn_abCdeF1gH2iJ3kL4mN'
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: The error code.
          example: '400'
        message:
          type: string
          description: A detailed error message.
          example: 'Invalid input'