FROM rabbitmq:3.8.29-management

# Expose RabbitMQ ports
EXPOSE 5672 15672

# Optional: Add custom configuration or plugins
# COPY ./rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
# COPY ./enabled_plugins /etc/rabbitmq/enabled_plugins
USER 10014
