openapi: 3.0.1
info:
  title: Booklisting
  version: 0.1.0
servers:
- url: "{server}:{port}/booklisting"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /books:
    get:
      operationId: getBooks
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /book:
    post:
      operationId: postBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookData'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    Book:
      type: object
      allOf:
      - $ref: '#/components/schemas/BookData'
      - required:
        - created_at
        - id
        type: object
        properties:
          id:
            type: integer
            format: int64
          created_at:
            type: string
        additionalProperties: false
    BookData:
      required:
      - author
      - isbn
      - metadata
      - name
      - publisher
      type: object
      properties:
        name:
          type: string
        author:
          type: string
        synopsis:
          type: string
        isbn:
          type: string
        publisher:
          type: string
        metadata:
          type: object
      additionalProperties: false
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
