version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: bookstore
      MYSQL_USER: appuser
      MYSQL_PASSWORD: supersecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
